#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDWalls.Code.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WPDB")]
	public partial class WallDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertWallpaper(Wallpaper instance);
    partial void UpdateWallpaper(Wallpaper instance);
    partial void DeleteWallpaper(Wallpaper instance);
    #endregion
		
		public WallDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WPDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WallDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WallDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WallDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WallDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Wallpaper> Wallpapers
		{
			get
			{
				return this.GetTable<Wallpaper>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetRandomWalls")]
		public ISingleResult<spGetRandomWallsResult> spGetRandomWalls([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(50)")] string iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CatName", DbType="VarChar(50)")] string catName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, catName);
			return ((ISingleResult<spGetRandomWallsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wallpapers")]
	public partial class Wallpaper : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _ID;
		
		private string _Title;
		
		private string _CatName;
		
		private string _FileFullPath;
		
		private string _OrgURL;
		
		private string _Tags;
		
		private System.Nullable<int> _Counter;
		
		private string _OrgFile;
		
		private System.Nullable<int> _DownloadTime;
		
		private string _OriginalSize;
		
		private string _SmallSize;
		
		private string _OrderNum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnCatNameChanging(string value);
    partial void OnCatNameChanged();
    partial void OnFileFullPathChanging(string value);
    partial void OnFileFullPathChanged();
    partial void OnOrgURLChanging(string value);
    partial void OnOrgURLChanged();
    partial void OnTagsChanging(string value);
    partial void OnTagsChanged();
    partial void OnCounterChanging(System.Nullable<int> value);
    partial void OnCounterChanged();
    partial void OnOrgFileChanging(string value);
    partial void OnOrgFileChanged();
    partial void OnDownloadTimeChanging(System.Nullable<int> value);
    partial void OnDownloadTimeChanged();
    partial void OnOriginalSizeChanging(string value);
    partial void OnOriginalSizeChanged();
    partial void OnSmallSizeChanging(string value);
    partial void OnSmallSizeChanged();
    partial void OnOrderNumChanging(string value);
    partial void OnOrderNumChanged();
    #endregion
		
		public Wallpaper()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatName", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string CatName
		{
			get
			{
				return this._CatName;
			}
			set
			{
				if ((this._CatName != value))
				{
					this.OnCatNameChanging(value);
					this.SendPropertyChanging();
					this._CatName = value;
					this.SendPropertyChanged("CatName");
					this.OnCatNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileFullPath", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string FileFullPath
		{
			get
			{
				return this._FileFullPath;
			}
			set
			{
				if ((this._FileFullPath != value))
				{
					this.OnFileFullPathChanging(value);
					this.SendPropertyChanging();
					this._FileFullPath = value;
					this.SendPropertyChanged("FileFullPath");
					this.OnFileFullPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgURL", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string OrgURL
		{
			get
			{
				return this._OrgURL;
			}
			set
			{
				if ((this._OrgURL != value))
				{
					this.OnOrgURLChanging(value);
					this.SendPropertyChanging();
					this._OrgURL = value;
					this.SendPropertyChanged("OrgURL");
					this.OnOrgURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tags", DbType="NVarChar(500)")]
		public string Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				if ((this._Tags != value))
				{
					this.OnTagsChanging(value);
					this.SendPropertyChanging();
					this._Tags = value;
					this.SendPropertyChanged("Tags");
					this.OnTagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Counter", DbType="Int")]
		public System.Nullable<int> Counter
		{
			get
			{
				return this._Counter;
			}
			set
			{
				if ((this._Counter != value))
				{
					this.OnCounterChanging(value);
					this.SendPropertyChanging();
					this._Counter = value;
					this.SendPropertyChanged("Counter");
					this.OnCounterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgFile", DbType="NVarChar(500)")]
		public string OrgFile
		{
			get
			{
				return this._OrgFile;
			}
			set
			{
				if ((this._OrgFile != value))
				{
					this.OnOrgFileChanging(value);
					this.SendPropertyChanging();
					this._OrgFile = value;
					this.SendPropertyChanged("OrgFile");
					this.OnOrgFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DownloadTime", DbType="Int")]
		public System.Nullable<int> DownloadTime
		{
			get
			{
				return this._DownloadTime;
			}
			set
			{
				if ((this._DownloadTime != value))
				{
					this.OnDownloadTimeChanging(value);
					this.SendPropertyChanging();
					this._DownloadTime = value;
					this.SendPropertyChanged("DownloadTime");
					this.OnDownloadTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalSize", DbType="VarChar(50)")]
		public string OriginalSize
		{
			get
			{
				return this._OriginalSize;
			}
			set
			{
				if ((this._OriginalSize != value))
				{
					this.OnOriginalSizeChanging(value);
					this.SendPropertyChanging();
					this._OriginalSize = value;
					this.SendPropertyChanged("OriginalSize");
					this.OnOriginalSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallSize", DbType="VarChar(500)")]
		public string SmallSize
		{
			get
			{
				return this._SmallSize;
			}
			set
			{
				if ((this._SmallSize != value))
				{
					this.OnSmallSizeChanging(value);
					this.SendPropertyChanging();
					this._SmallSize = value;
					this.SendPropertyChanged("SmallSize");
					this.OnSmallSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNum", DbType="VarChar(50)")]
		public string OrderNum
		{
			get
			{
				return this._OrderNum;
			}
			set
			{
				if ((this._OrderNum != value))
				{
					this.OnOrderNumChanging(value);
					this.SendPropertyChanging();
					this._OrderNum = value;
					this.SendPropertyChanged("OrderNum");
					this.OnOrderNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spGetRandomWallsResult
	{
		
		private int _Code;
		
		private string _ID;
		
		private string _Title;
		
		private string _CatName;
		
		private string _FileFullPath;
		
		private string _OrgURL;
		
		private string _Tags;
		
		private System.Nullable<int> _Counter;
		
		private string _OrgFile;
		
		private System.Nullable<int> _DownloadTime;
		
		private string _OriginalSize;
		
		public spGetRandomWallsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatName", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string CatName
		{
			get
			{
				return this._CatName;
			}
			set
			{
				if ((this._CatName != value))
				{
					this._CatName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileFullPath", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string FileFullPath
		{
			get
			{
				return this._FileFullPath;
			}
			set
			{
				if ((this._FileFullPath != value))
				{
					this._FileFullPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgURL", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string OrgURL
		{
			get
			{
				return this._OrgURL;
			}
			set
			{
				if ((this._OrgURL != value))
				{
					this._OrgURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tags", DbType="NVarChar(500)")]
		public string Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				if ((this._Tags != value))
				{
					this._Tags = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Counter", DbType="Int")]
		public System.Nullable<int> Counter
		{
			get
			{
				return this._Counter;
			}
			set
			{
				if ((this._Counter != value))
				{
					this._Counter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgFile", DbType="NVarChar(500)")]
		public string OrgFile
		{
			get
			{
				return this._OrgFile;
			}
			set
			{
				if ((this._OrgFile != value))
				{
					this._OrgFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DownloadTime", DbType="Int")]
		public System.Nullable<int> DownloadTime
		{
			get
			{
				return this._DownloadTime;
			}
			set
			{
				if ((this._DownloadTime != value))
				{
					this._DownloadTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalSize", DbType="VarChar(50)")]
		public string OriginalSize
		{
			get
			{
				return this._OriginalSize;
			}
			set
			{
				if ((this._OriginalSize != value))
				{
					this._OriginalSize = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
