<?xml version="1.0" encoding="utf-8"?><Database Name="WPDB" Class="WallDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=WPDB;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WPDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Wallpapers" Member="Wallpapers">
    <Type Name="Wallpaper">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CatName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="FileFullPath" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="OrgURL" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Counter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrgFile" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DownloadTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OriginalSize" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SmallSize" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="OrderNum" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.spGetRandomWalls" Method="spGetRandomWalls">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CatName" Parameter="catName" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="spGetRandomWallsResult">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CatName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="FileFullPath" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="OrgURL" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Counter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrgFile" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DownloadTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OriginalSize" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>